import os
import io
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── 1. Safe Font Registration ──────────────────────────────────────────────────
try:
    # Try to load system fonts
    pdfmetrics.registerFont(TTFont('Arial', 'C:\\Windows\\Fonts\\arial.ttf'))
    pdfmetrics.registerFont(TTFont('Arial-Bold', 'C:\\Windows\\Fonts\\arialbd.ttf'))
    pdf_font = "Arial"
    pdf_font_bold = "Arial-Bold"
except:
    # Fallback to standard PDF fonts if Arial is not found
    pdf_font = "Helvetica"
    pdf_font_bold = "Helvetica-Bold"

# ── 2. Colour Palette ─────────────────────────────────────────────────────────
C_BG         = HexColor('#F1F8E9')   # Page background
C_HEADER_BG  = HexColor('#2E7D32')   # Header green
C_HEADER_TXT = HexColor('#FFFFFF')
C_ACCENT     = HexColor('#66BB6A')
C_CARD_BG    = [HexColor('#FFF9C4'), HexColor('#FCE4EC'), HexColor('#E3F2FD'), HexColor('#F3E5F5'), HexColor('#E8F5E9')]
C_CARD_BORDER= [HexColor('#F9A825'), HexColor('#E91E63'), HexColor('#1E88E5'), HexColor('#8E24AA'), HexColor('#43A047')]
C_CARD_TXT   = [HexColor('#5D4037'), HexColor('#880E4F'), HexColor('#0D47A1'), HexColor('#4A148C'), HexColor('#1B5E20')]
C_SCORE_BG   = HexColor('#A5D6A7')

# ── 3. Helper Functions ───────────────────────────────────────────────────────

def _draw_background(c, width, height):
    """Draws the main sage background."""
    c.setFillColor(C_BG)
    c.rect(0, 0, width, height, fill=1, stroke=0)

def _draw_decorative_corner_dots(c, width, height):
    """Adds decorative circles to corners."""
    positions = [(30, height - 10), (width - 30, height - 10), (30, 50), (width - 30, 50)]
    for (cx, cy) in positions:
        for r in [3, 6, 9]:
            c.setFillColor(C_ACCENT)
            c.setFillAlpha(0.3 - r * 0.025)
            c.circle(cx, cy, r, fill=1, stroke=0)
    c.setFillAlpha(1.0)

def _draw_header(c, width, height, growth_form):
    """Draws the top green header band."""
    band_h = 110
    band_y = height - band_h
    c.setFillColor(C_HEADER_BG)
    c.rect(0, band_y, width, band_h, fill=1, stroke=0)
    
    c.setFillColor(C_HEADER_TXT)
    c.setFont(pdf_font_bold, 22)
    c.drawCentredString(width / 2, band_y + 72, 'PlantVeda Analysis')
    
    c.setFont(pdf_font, 10)
    c.setFillColor(C_ACCENT)
    c.roundRect((width-220)/2, band_y+18, 220, 22, 11, fill=1, stroke=0)
    c.setFillColor(C_HEADER_TXT)
    c.drawCentredString(width/2, band_y+25, f'Predicted Growth Form: {growth_form}')

def _draw_meta_row(c, width, height, habitat, soil, area, budget, ts):
    """Draws the metadata information bar."""
    meta_y = height - 138
    c.setFont(pdf_font, 8.5)
    c.setFillColor(HexColor('#4E7A4F'))
    meta_text = f"Habitat: {habitat}  |  Soil: {soil}  |  Area: {area}m²  |  Budget: Rs.{budget}  |  {ts}"
    c.drawString(30, meta_y, meta_text)
    c.setStrokeColor(C_ACCENT)
    c.line(30, meta_y - 5, width - 30, meta_y - 5)

def _draw_plant_card(c, rank, plant_dict, x, y, card_w, card_h):
    """Draws a single plant result card."""
    idx = rank - 1
    bg, bdr, txt = C_CARD_BG[idx], C_CARD_BORDER[idx], C_CARD_TXT[idx]
    
    # Card Body
    c.setFillColor(bg)
    c.setStrokeColor(bdr)
    c.roundRect(x, y, card_w, card_h, 12, fill=1, stroke=1)
    
    # Left Border Strip
    c.setFillColor(bdr)
    c.roundRect(x, y, 8, card_h, 4, fill=1, stroke=0)
    
    # Text Data
    c.setFillColor(txt)
    c.setFont(pdf_font_bold, 14)
    c.drawString(x + 25, y + card_h - 25, f"#{rank} {plant_dict['name']}")
    
    c.setFont(pdf_font, 9)
    stats = f"Count: {plant_dict['count']} | Carbon: {plant_dict['carbon']}kg | Cost: Rs.{plant_dict['cost_per_unit']}"
    c.drawString(x + 25, y + 15, stats)

# ── 4. Main Public Function ──────────────────────────────────────────────────

def generate_pdf(recommended_plants, growth_form, habitat, soil, total_area, total_cost):
    buffer = io.BytesIO()  # ← memory buffer instead of file
    c = canvas.Canvas(buffer, pagesize=A4)  # ← write to buffer
    width, height = A4
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    _draw_background(c, width, height)
    _draw_decorative_corner_dots(c, width, height)
    _draw_header(c, width, height, growth_form)
    _draw_meta_row(c, width, height, habitat, soil, total_area, total_cost, timestamp)

    card_w = width - 80
    card_h = 75
    start_y = height - 230

    for i, plant in enumerate(recommended_plants[:5]):
        y_pos = start_y - (i * (card_h + 15))
        _draw_plant_card(c, i + 1, plant, 40, y_pos, card_w, card_h)

    c.setFont(pdf_font, 7)
    c.setFillColor(HexColor('#757575'))
    c.drawCentredString(width/2, 20, "Generated by PlantVeda Intelligence Engine")

    c.save()
    buffer.seek(0)  # ← rewind before returning
    return buffer   # ← return buffer instead of filename
